### ISSUE TITLE
Options min_len and max_len throw an error or do not work

### ISSUE THREAD

**Issue by mw55309** [bcgsc/NanoSim#10]
Trying to use min_len gives:

python NanoSim/src/simulator.py linear -r ecoli.fa -c projects/cheny_prj/nanopore/paper/R9/1D/ecoli -n 500 --min_len 1500
./simulator.py [command] <options>
[command] circular | linear
Do not choose 'circular' when there is more than one sequence in the reference
<options>:
-h : print usage message
-r : reference genome in fasta file, specify path and file name, REQUIRED
-c : The prefix of training set profiles, same as the output prefix in read_analysis.py, default = training
-o : The prefix of output file, default = 'simulated'
-n : Number of generated reads, default = 20,000 reads
--max_len : Maximum read length, default = Inf
--min_len : Minimum read length, default = 50
--perfect: Output perfect reads, no mutations, default = False
--KmerBias: prohibits homopolymers with length >= n bases in output reads, default = 6

Trying to use max_len gives an error:

python NanoSim/src/simulator.py linear -r ecoli.fa -c projects/cheny_prj/nanopore/paper/R9/1D/ecoli -n 500 --max_len 1000
Traceback (most recent call last):
  File "NanoSim/src/simulator.py", line 671, in <module>
    main()
  File "NanoSim/src/simulator.py", line 665, in main
    simulation(ref, out, dna_type, perfect, kmer_bias, max_readlength, min_readlength)
  File "NanoSim/src/simulator.py", line 344, in simulation
    read_mutated = ''.join(np.random.choice(BASES, head)) + read_mutated
AttributeError: 'module' object has no attribute 'choice'

**Comment by cheny19** [comment]
Thanks for pointing out the bug about `--min_len`, I fixed the bug and it's working now.

For `max_len`, I could not reproduce this error message. When I search for the answer online, some people mentions it might be because of other files called `random` exists in your path, so Python doesn't know which one to use, your file or the module in `numpy`. 

See this thread: [http://stackoverflow.com/questions/25695412/module-object-has-no-attribute-choice-trying-to-use-random-choice](url)

If it's not the case, it would be better for me to debug if you could provide your training dataset.
