### ISSUE TITLE
No such file or directory: 'human_strandness_rate'

### ISSUE THREAD

**Issue by manojwustl** [bcgsc/NanoSim#137]
I am getting following error with command: simulator.py genome -dna_type linear -rg hg19.fa -c human -max 10000 -min 1000

    with open(model_prefix + "_strandness_rate", 'r') as strand_profile:
FileNotFoundError: [Errno 2] No such file or directory: 'human_strandness_rate'

**Comment by SaberHQ** [comment]
Hey @manojwustl 

May I ask whether you trained your own model (using read_analysis script) or you are using one of the [pre-trained models](https://github.com/bcgsc/NanoSim/tree/master/pre-trained_models) provided along with NanoSim? If it is the later case, what is the pre-trained model you are using?

**Comment by SaberHQ** [comment]
Dear @manojwustl 

It is been a while since our last conversation. I hope you were able to run NanoSim and get your results. `strandness_rate` is calculated during the training stage. Please make sure you ran that phase successfully. 

I am closing the issue for now. Please feel free to reopen it if you still got question regarding this. Thanks.
