### ISSUE TITLE
Effect of `-b` in metagenome mode

### ISSUE THREAD

**Issue by ezherman** [bcgsc/NanoSim#212]
Hi,

The `-b` flag is said to affect the "homopolymers and/or base qualities with respect to chosen basecaller". I was hoping to clarify what the effect of this parameter is when using a model that was trained on Dorado basecalled data. Can I expect the base qualities to mimic those of he data that went into the characterisation stage? If so, what will the effect be of changing the `-b` parameter?

Thanks!

**Comment by ezherman** [comment]
Update: we found that simulating with `-b guppy` using a model trained on Dorado basecalled data returned reads with an average Q score of approximately 8. 

Additionally, we found that changing the values in [trunc_lognorm_rvs](https://github.com/bcgsc/NanoSim/blob/master/src/mixed_model.py#L80) resulted in changed base qualities. Is there any documentation on how these values were estimated? We'd like to have a go at estimating these on our Dorado basecalled data.

If relevant, would it be possible to get your thoughts @SaberHQ @kmnip? Thanks in advance!

**Comment by SaberHQ** [comment]
Dear @ezherman Thanks for your interest in using NanoSim and sorry for the late reply since I was away from work. 

I am currently working on a version release for NanoSim which incorporates the characterization of homopolymer lengths and base qualities so that there will be no need for hard coded values as you pointed out at [trunc_lognorm_rvs](https://github.com/bcgsc/NanoSim/blob/master/src/mixed_model.py#L80)

Those values are based on my colleague's (@theottlo) analysis of various ONT reads and in NanoSim's latest release (which should be ready within the next day or two), we will include the calculation of those metrics within NanoSim main code. 

I will keep you updated here once I push the new release. 

Saber.

**Comment by ezherman** [comment]
Hi @SaberHQ, thnk you for getting back to me. This sounds exciting! I'm looking forward to working with your new release.

**Comment by SaberHQ** [comment]
Hi @ezherman. Please note that I just published a [new release](https://github.com/bcgsc/NanoSim/releases/tag/v3.2.0) for NanoSim. This includes the new feature I talked about and I hope it addresses your issue.

**Comment by ezherman** [comment]
Thanks @SaberHQ, I'm looking forward to giving the new version a go!
