### ISSUE TITLE
Simulation of Rolling Circle Amplification Data

### ISSUE THREAD

**Issue by Le1223** [bcgsc/NanoSim#216]
Hello,
I would like to simulate ONT rolling circle amplification data. Can the NanoSim software be used for this purpose?

Best wishes,

**Comment by SaberHQ** [comment]
Hi @Le1223 . Thanks for your interest in using NanoSim. 

NanoSim is a base-level simulator which utilizes statistical models to learn the characteristics of sequencing libraries and then applies those models to simulate ONT reads. This means that it relies on input ONT reads in its characterization stage to learn their features including the length distribution and error rates and profiles. 

I am not very familiar with Rolling Circle Amplification but I wonder if various basecaller algorithms can detect sets of nanopore signals related to RCA? If yes, which tools? I also wonder if RCA is detectable with specific flowcell and pore chemistries? Answers to these questions might be helpful for you to see if NanoSim and its pre-characterized models would be suitable for your task. 

If you have a set of reads sequenced and basecalled using RCA in library preparation, then I would suggest you to use those reads as input to NanoSim characterization stage ([read_analysis.py](https://github.com/bcgsc/NanoSim/blob/master/src/read_analysis.py)) and then utilize the trained models to simulate similar read sets. 

Currently, we have no plans to add new features to NanoSim. Please read the respective NanoSim papers to gain more insights about its workflow, features, and limitations. 

[Genome](https://doi.org/10.1093/gigascience/gix010)
[Transcriptome](https://doi.org/10.1093/gigascience/giaa061)
[Meta-genome](https://doi.org/10.1093/gigascience/giad013)

With that being said, I am closing this issue. Please feel free to re-open it or ask more questions and we will be happy to assist you. 

Best, 
Saber.

**Comment by Le1223** [comment]
Thank you for your reply.

The data generated from rolling circle amplification often contains a large number of tandem repeat sequences within the reads. When I use my post-amplification data in read_analysis to simulate genome data, the simulated results do not include tandem repeat sequences. Considering this similarity to chimeric sequences, I also added the --chimeric parameter during the simulation, but the results still do not include tandem repeat sequences. I am uncertain if NanoSim is capable of simulating tandem repeat sequences.

Best,

**Comment by SaberHQ** [comment]
Thanks for the information and clarification on tandem repeat sequences. Its indeed an interesting topic to explore.

NanoSim is not natively designed to characterize and simulate tandem repeats (TRs). That being said, I believe that you should modify the reference genome you are using in your analysis in order to simulate TRs.

In the characterization stage, NanoSim aligns the ONT reads to reference genome used and then based on the alignment file, it models the length distribution of ONT reads as well as other features such as their error profiles. If you align the RCA-reads to your reference genome, those TRs would not align to the reference genome and hence characterize as error. 

My colleague, @readmanchiu, developed [Straglr](https://link.springer.com/article/10.1186/s13059-021-02447-3), a tool for discovering and genotyping tandem repeat expansions using whole genome long-read sequences. NanoSim was used in that study and I suggest you to take a look at that paper and reach out to him for more questions. 

I added a `feature request` tag to this issue and we might consider it in future developments and version releases. Thanks.

Saber.
