### ISSUE TITLE
Minimap2 vs Last running time

### ISSUE THREAD

**Issue by npavlovikj** [bcgsc/NanoSim#28]
Hi,

I tried "NanoSim-2.0" with both "minimap2" and "last" on my data.
The  alignment finishes quickly; however, the run with "minimap2" took 10 hours compared to the run with "last" that took about an hour.

For "minimap2", you can see below that there have been almost 10 hours before the simulation was reported as finished.
**2018-05-01 02:44:54: Model fitting
2018-05-01 12:20:20: Finished!**
while for "last" on the same data, there has been only an hour:
**2018-05-01 02:51:10: Model fitting
2018-05-01 03:43:43: Finished!**

This is when I ran "read_analysis.py", so I was wondering if this is normal, or I am missing some optimization step for "minimap2"? I did use "minimap2" with 4 threads.

Thank you,
Natasha

**Comment by cheny19** [comment]
Hi Natasha,

When NanoSim enters model fitting phase, it has nothing to do with the aligner any more. `read_analysis.py` was trying to find the best parameter combinations for the error model and it took nearly 10 hours for the alignment results from `minimap2`. Could you send me your alignment files or raw data so I can test? I'm curious why it took so long.

Thanks,
Chen

**Comment by cheny19** [comment]
Hi Natasha,

Sorry I didn't reply until now. Last few weeks I looked into the code and I think the runtime is heavily dragged down by R. So I re-wrote the model fitting part in Python (which is faster than R) and it now supports multiprocessing. The model fitting stage can be finished within a hour now. Please download the latest commit and have a try. I haven't made the new release yet, because I have more testing to do, but on your dataset, it works fine.

The error model is a bit different between `minimap2` and `LAST`, and the original proposed model may not fit very well on errors inferred from `minimap2`. That is also why it ran for so long in previous versions. NanoSim will throw a warning if the fitted model cannot pass statistical test, but don't worry, it's still close to the emprical errors. I'll keep looking and see if there are better models.

Thanks for pointing this out!
