### ISSUE TITLE
"Index out of range" Error in read_analysis.py

### ISSUE THREAD

**Issue by zhouanbo** [bcgsc/NanoSim#29]
When tested, the read_analysis.py step outputs the following message after minimap2 alignment:
```
2018-06-26 02:00:48: Read pre-process and unaligned reads analysis
2018-06-26 02:01:23: Alignment with minimap2
2018-06-26 03:39:49: Aligned reads analysis
2018-06-26 04:12:57: match and error models
Traceback (most recent call last):
  File "/lab01/Tools/NanoSim-2.0.0/src/read_analysis.py", line 202, in <module>
    main(sys.argv[1:])
  File "/lab01/Tools/NanoSim-2.0.0/src/read_analysis.py", line 186, in main
    error_model.hist(prefix, file_extension)
  File "/lab01/Tools/NanoSim-2.0.0/src/besthit_to_histogram.py", line 330, in hist
    add_dict(list_hist[i], dic_mis)
IndexError: list index out of range
```
The input is a downloaded a fastq file from Nanopore WGS Consortium for NA12878 and converted to fasta using seqtk. The reference is GRCh38. I've tested both version 2.1.0 and version 2.0.0.

**Comment by cheny19** [comment]
I randomly downloaded one flowcell from the Nanopore WGS Consortium [NA12878](https://github.com/nanopore-wgs-consortium/NA12878/blob/master/Genome.md) and tried V2.1.0, but cannot re-produce the error. Could you send me your dataset so I can debug? Thanks!

**Comment by zhouanbo** [comment]
Thanks for the reply! Sure, the command I'm using is 
```
python3 /lab01/Tools/NanoSim/src/read_analysis.py -I /nfs/.../rel3-nanopore-wgs-152889212-FAB45271.fasta -r /nfs/.../GRCh38_full_analysis_set_plus_decoy_hla.fa
```
I also randomly picked a file, the link is 
```
http://s3.amazonaws.com/nanopore-human-wgs/rel3-nanopore-wgs-152889212-FAB45271.fastq.gz
```
I then gunzipped it and used seqtk to convert to fasta:
```
./seqtk seq -a /nfs/.../rel3-nanopore-wgs-152889212-FAB45271.fastq > /nfs/.../rel3-nanopore-wgs-152889212-FAB45271.fasta
```

**Comment by cheny19** [comment]
I downloaded the above file and converted it, but still, I didn't see any error. Our commands differ in the following steps:

1. `./seqtk seq` I used `-A` instead of `-a` because the version I used doesn't have `-a` option. Please check your fasta file and make sure it's correct.

2. The reference genome maybe different. Mine doesn't have any patches, only 24 chromosomes. I don't think it should cause the problem, but try to remove the patches and give it a shot. 

3. `read_analysis.py` actually don't have `-I` option, it's actually `-i`, although I don't think it's the reason either.

Also, please check if your `minimap2` run succeeded and make sure the `.sam` file is not empty. If you still can't get rid of the error, please share your alignment file and I'll start from there.

**Comment by zhouanbo** [comment]
Hi Chen,
Sorry the LAST alignment took a few days. 
I did two things:
1. I first use NanoSim 1.3 which has the read_analysis.py unmodified, and it processed the same fasta file ok.
2. I cut the first 100 line from fasta the file, and ran with NanoSim 2.1.0, it also runs ok.
So I think there should be something in the fasta file that's incompatible. To check the file is alright, I downloaded it again and went through the same procedure, the md5sum checks out, it's 1c1bb3fd8625cbb45e41c058422923ed. I'm also attaching a link of that file from google drive for you reference: https://drive.google.com/open?id=1dSEeMGrF64zFVnJfvI6ENnc-By8K_PeH
Thanks again for your help!
Anbo.

**Comment by zhouanbo** [comment]
Hi, 
I have the package version as following:
python (3.6.3)
HTSeq (0.10.0)
numpy (1.14.5)
pybedtools (0.7.10)
pysam (0.14.1)
scipy (1.1.0)
six (1.11.0)
I ran NanoSim on another server and it runs successfully. I suspect it's because I'm running it on Centos 6.3 and the system is too old. 
Thanks for the help tho!
