### ISSUE TITLE
Read length distribution unexpected peaks 

### ISSUE THREAD

**Issue by georgiab7** [bcgsc/NanoSim#31]
I used the following commands to simulate reads for an E.coli strain from the NCBI database, I simulated 2 sets of reads with different length parameters but in both cases when I plotted the distribution of read lengths, regular but unexpected peaks in frequency of certain read lengths can be seen. 
Is there an explanation for this and is it avoidable? 

`~/NanoSim-2.1.0$simulator.py circular -r ../MG1655_reference.fasta -c ecoli -n 200000 -o MG1655_Q3_simulation  --max_len 2500

~/NanoSim-2.1.0$simulator.py circular -r ../MG1655_reference.fasta -c ecoli -n 200000 -o MG1655_Q2_simulation  --min_len 2500 --max_len 5000`

![screen shot 2018-07-10 at 2 23 39 pm](https://user-images.githubusercontent.com/25476884/42485688-e07a32a8-844c-11e8-8fbf-fbd72f6d81d1.png)

**Comment by cheny19** [comment]
NanoSim tries to simulate the length distribution from the profile. Do you also see this type of peaks in your ecoli profile? If so, that means NanoSim is simply doing its job. If not, please send me your training data and I'll investigate more into this issue. Thanks!

**Comment by georgiab7** [comment]
I used the default R9 1D E.coli profile provided with Nanosim, Thanks

**Comment by harisankar991** [comment]
Any leads on why this is observed?

**Comment by harisankar991** [comment]
Did you see the similar peaks with the training dataset as well? Any leads on this?

**Comment by cheny19** [comment]
I finally got time to sit down and seriously look at this issue. I don't see similar peaks with the training set, but I'll need to inspect more to figure it and fix this behaviour.

**Comment by cheny19** [comment]
@georgiab7 Sorry about the late reply. After some careful inspection, I found that this behaviour is due to the binning strategy in simulating align ratio of each reads. Basically during training, all reads are divided into several bins according to their length and each bin has its own ECDF to be simulated. Using this strategy, the general CDF of total read length and align ratio can be captured quite well, but thanks to you, we noticed that there some spikes in the PDF/histogram. 

I hope this didn't affect your work with the simulated data. And we currently are trying to find a better way to simulate the align ratio and will incorporate it in our next release. Stay tuned!

**Comment by FiniDG-HAN** [comment]
I also find a weird peak in the original publically available data minION fastq files (so not by NanoSim). 
![logtransformed_histogramreadlength](https://user-images.githubusercontent.com/31845711/48612173-76a2b980-e988-11e8-82c2-d0798ad0b56c.png)

And I found out via this webpage [nr1](https://www.researchgate.net/figure/MinION-read-length-histogram-A-histogram-of-2D-read-lengths-from-7300-MinION-reads-The_fig1_285746062) and [nr2](https://www.sciencedirect.com/science/article/pii/S2214753515000224) that this is called a spike-in, which they put in there deliberately. Maybe if you train with this, it results in these peaks as well?

not sure if related, but I want to know, because I don't know if I am able to remove these reads?

**Comment by cheny19** [comment]
Thanks for the inspection! However the peaks in simulated reads based on R9 1D E. coli profile are different from the spike-in sequences here @FiniDG-HAN. To remove the spike-in data, you can do a sequence alignment against the spike-in reference and remove the aligned reads. Normally the spike-in sequences are manually generated and there should be a reference for them.

**Comment by cheny19** [comment]
@georgiab7 and @FiniDG-HAN, we recently changed the simulation algorithm and used Kernel Density Functions to simulate the read lengths and align ratios on each reads. Simulated reads using this strategy do not have these peaks and the read lengths are more smooth. Distributions of the length of unaligned region, length of aligned region, and total read length are closer to the training data than previsous releases. Please download the latest version and give it a shot. Thanks for your patience!
