### ISSUE TITLE
NanoSim Simulation and reference use

### ISSUE THREAD

**Issue by belaidH** [bcgsc/NanoSim#52]
Hi,
I'm actually working with NanoSim to simulate reads from customized reference:
to do That I'm using:
 - predefined  error profile (from nanosim-h) which is ecoli_R9_1D.
 - 2 differents customized references (to see the impact of homopolymers on reads).
But according to my results, I think that change the reference file has no impact on reads simulation the error profile put same errors type and number for same read length sequences.
Is my results correct  (i.e nanoSim use just the error profile) or it consider the reference file (number of homopolymers and other things) ?
thank's.

**Comment by cheny19** [comment]
Hi,

I'm not sure about the reason. Could you provide me with the command you used for the two different references?

Thanks,
Chen

**Comment by belaidH** [comment]
Hi Chen,

This is the commands:

>nanosim-h -n100 --max-len 15000 --min-len 25000 -p ecoli_R9_1D reference1.fa

>nanosim-h -n100 --max-len 15000 --min-len 25000 -p ecoli_R9_1D reference2.fa

The references has same length.

(So NanoSim lookat homopolymers length ?)

Thanks,

**Comment by cheny19** [comment]
Sorry for the late reply. It seems you were asking for min_len to be larger than max_len based on the commands above.

**Comment by SaberHQ** [comment]
Dear @belaidH 

NanoSim models the error rate, length distribution and other characteristics of the input read and then in the simulation stage, you give it a reference and NanoSim applies those profile and produces some synthetic reads.

Therefore, it means that when you use a predefined model, no matter if you change the reference file in the simulation stage, your simulated reads are going to have similar error rates and length distribution. That's because you use the same profiles for both of them!

I hope it explains your question. Besides, as Chen suggested, you are setting min length higher than max length which is not correct. 

Finally, use the latest version, read the documentation and README file and let me know if I can be of more help. I am closing this issue now.
