### ISSUE TITLE
Simulator fails using different reads 

### ISSUE THREAD

**Issue by ml12220** [bcgsc/NanoSim#6]
Hi, 
The read_analysis.py and simulator.py steps are working fine when I use the supplied ecoli and yeast reads in the profile stage. However, when I use Nick Lomans MAP-006-2 reads ( http://lab.loman.net/2015/09/24/first-sqk-map-006-experiment/ ) I get this error in the simulation stage:

> 
> Traceback (most recent call last):
>   File "/home/mike/NanoSim/src/simulator.py", line 643, in <module>
>     main()
>   File "/home/mike/NanoSim/src/simulator.py", line 635, in main
>     read_profile(number, model_prefix, perfect)
>   File "/home/mike/NanoSim/src/simulator.py", line 149, in read_profile
>     number_aligned = int(round(number * float(rate) / (float(rate) + 1)))
> ValueError: invalid literal for float(): 100%

These were my commands:

> read_analysis.py -i ecoli_K12_MG1655_ref.fa -r MAP006-2_2D_pass.fasta -o MAP
> 
> simulator.py circular -r Pmarinus.fasta -c MAP -n 10 -o pmarinus_MAP_10
> 

This data set has longer reads (>9kbp) and higher accuracy than the supplied data sets I think.
Any ideas?

Many thanks,
Mike

**Comment by JustinChu** [comment]
Luckily, I was able to reproduce the error quickly because I actually already had this dataset on hand. Thanks for letting us know. We will try to have a fix soon ASAP.

I fixed one bug related to this (a simple parsing error) but there still seems to be a bug related to the alignment ratio. The reads are indeed much better (longer and higher quality) than before. 100% of the read map and the average reads lengths are much longer This is causing problems in the creation of the `MAP_align_ratio` file created.

@cheny19 I'm now convinced that our pre-set bins sizes are not a good idea. All the reads are in the `align_ratio` file are migrating to the last bin (because the reads are so long), leaving every other bin empty, cause errors when loading this file. I can change the bins to scale to the data but I don't know what effect this will have on the modeling.

**Comment by cheny19** [comment]
Hi Mike,

Sorry I didn't get back to you earlier as I was on vacation.  
The binning problem is fixed now. I'm using equal number of reads in each bin now, and user can specify the number of bins they need. The default number of bins is 20.  
I still need to test and find out the best default value that works for most of the datasets, but right now, this version is ready to use. I tested it on your dataset and it works pretty well.

**Comment by ml12220** [comment]
That works fine now thanks!
