### ISSUE TITLE
MD flag not requested

### ISSUE THREAD

**Issue by baraaorabi** [bcgsc/NanoSim#65]
I am getting an `KeyError: 'SAM optional field tag MD not found'` but the README does not specify that

**Comment by cheny19** [comment]
Thanks for pointing it out! Just added that to the README!

**Comment by jluebeck** [comment]
Since the MD tag is required, should it be specified as part of the minimap2 command? That is, should `--MD` be added to the minimap2 commands that `read_analysis.py` runs in order to generate the .sam file? It seems that it is not currently added as I receive a similar errror when generating the .sam file with read_analysis.py, but related to the cs tag (which is also not placed by default it seems).
